### PR TITLE
Second set of fixes

### PR DESCRIPTION
**Pull request by jdfreder**
- Load css
- Inherit from DOMWidget (how did it ever work without this!?)
- Use ES6 promise logic correctly

### CODE REVIEW

**Comment by jdfreder** [comment]
@cekees with these changes I'm able to use the DrawControl notebook completely.  Please let me know if there's anything else missing.

**Comment by cekees** [comment]
Great! I've only found one problem so far, that's in the GeoJSON notebook when it removes a layer:

```
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined {stack: (...), message: "Cannot read property 'id' of undefined"}message: "Cannot read property 'id' of undefined"stack: (...)get stack: function () { [native code] }arguments: nullcaller: nulllength: 0name: ""prototype: StackTraceGetter__proto__: function Empty() {}<function scope>set stack: function () { [native code] }__proto__: Errorwidget.DOMWidgetView.extend.remove_layer_model @ leafletwidget.js?v=20150521171811:381(anonymous function) @ widget.js?v=20150521171811:723
```

**Comment by cekees** [comment]
I put the images directory in the wrong place, so some of the markers aren't displaying, but I'm fixing that.

**Comment by jdfreder** [comment]
Ok, the last commit should fix the layer removal.  It turns out I was doing something wrong with the ViewList, but it should be fixed now.

**Comment by cekees** [comment]
Thanks!

**Pull request merged**
